baseURL = 'https://varshasbhat.github.io/blog/'
languageCode = 'en-us'
title = "varsha bhat"
theme = 'papermod'
publishDir = "docs"
[caches]
    [caches.images]
        dir = ':cacheDir/images'
[params]
defaultTheme = "dark"
disableThemeToggle =false
ShowReadingTime = true
ShowToc = true
ShowPostNavLinks=true


[params.homeInfoParams]
Title = "varsha thinks."
Content = "therefore, varsha's blog is."