baseURL = 'https://varshasbhat.github.io/blog'
languageCode = 'en-us'
title = "varsha has a blog now"
theme = 'papermod'
publishDir = "docs"
[caches]
    [caches.images]
        dir = ':cacheDir/images'