baseURL = 'https://varshasbhat.github.io/blog'
languageCode = 'en-us'
title = "Varsha's not Test Blog"
theme = 'papermod'
publishDir = "docs"
[caches]
    [caches.images]
        dir = ':cacheDir/images'